<a href="https://colab.research.google.com/github/StuartLance/PyTorch-Test/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
my_list = [[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

# Numpy Array
3 Rows, 4 Columns


In [6]:
np1 = np.random.rand(3,5)
np1

array([[0.14035296, 0.81489155, 0.40685346, 0.56222841, 0.69664005],
       [0.63146106, 0.63900254, 0.36835002, 0.37495785, 0.65045869],
       [0.04831767, 0.94332957, 0.12294883, 0.20064287, 0.60412777]])

# Tensor


In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.4043,  0.7830,  0.9493,  0.6029],
        [ 0.5669,  0.6004, -0.2462,  0.4014],
        [-1.2686, -1.2234, -1.3685, -0.1391]])

In [9]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.4144, -0.6723,  1.5836,  1.8150],
         [-0.0194, -0.9041,  1.5192,  0.0526],
         [-0.4177,  0.5738,  0.5515, -0.5745]],

        [[ 1.6230, -1.9813,  1.4683,  1.3442],
         [-1.0875, -0.3061,  1.5075,  0.2353],
         [ 0.6433, -1.5313, -0.0493, -0.5208]]])

In [10]:
# Tensor from numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1404, 0.8149, 0.4069, 0.5622, 0.6966],
        [0.6315, 0.6390, 0.3684, 0.3750, 0.6505],
        [0.0483, 0.9433, 0.1229, 0.2006, 0.6041]], dtype=torch.float64)